version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: egen
    ports:
      - "5432:5432"
  weg-api:
    image: weg-api
    build: .
    container_name: weg-api
    ports:
      - "8080:8080"
    depends_on:
      - "db"